### ISSUE TITLE
CD fails because of missing npm token

### ISSUE THREAD

**Issue by SebastianSpeitel** [ColinEberhardt/assemblyscript-temporal-tz#3]
see https://github.com/ColinEberhardt/assemblyscript-temporal-tz/runs/3641054303

**Comment by ColinEberhardt** [comment]
Yeah, I'm aware of this - I 'forked' this project from https://github.com/ColinEberhardt/assemblyscript-temporal, so carried the CD settings across. In the short-term I don't plan to run semantic release on this project just yet, it's a bit to 'beta'. I'll turn this off.
